### ISSUE TITLE
About time.Time deep copy

### ISSUE THREAD

**Issue by fufuok** [polyred/polyred#2]
Hello Kun:

After the time.Time type is deep copied, the local time zone will disappear, causing trouble for subsequent use. Is there any solution, thanks.

```go
func Test_Time(t *testing.T) {
	t1 := time.Now()
	t2 := deepcopy.Value(t1)
	if t1.String() != t2.String() {
		t.Logf("t1: %s, t2: %s", t1.Format(time.RFC3339), t2.Format(time.RFC3339))
		t.Logf("t1: %v, t2: %v", t1, t2)
		t.Fatalf("t1: %v, t2: %v", t1.Location(), t2.Location())
	}
}
```

```shell
=== RUN   Test_Time
    deepcopy_test.go:133: t1: 2022-12-26T09:25:19+08:00, t2: 2022-12-26T01:25:19Z
    deepcopy_test.go:134: t1: 2022-12-26 09:25:19.7355683 +0800 CST m=+0.000342001, t2: 2022-12-26 01:25:19.7355683 +0000 UTC m=+0.000342001
    deepcopy_test.go:135: t1: Local, t2:
--- FAIL: Test_Time (0.00s)
FAIL
```

**Comment by changkun** [comment]
Hi, I am not sure about your current usage because the deepcopy is in internal package and should not be callable from public in any case. What are you doing?

**Comment by fufuok** [comment]
I saw this proposal: https://go.dev/issue/51520, and your implementation.

I want to use it in my own project while retaining copyright. After testing, I found that there is the above time zone problem when deep copying time.Time.

**Comment by changkun** [comment]
Then this is the wrong place to discuss this topic because this repo is about graphics. Please report your questions here: https://github.com/golang-design/reflect
